services:
  # For storing the content and the reference id.
  db:
    image: postgres:13
    restart: always
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - llm_apis_postgres:/var/lib/postgresql/data

  # To interact with the llm.
  llm_middleware:
    image: busycaesar/llm_middleware_api
    restart: always
    env_file:
      - llm_middleware.env
    ports:
      - "7000:7000"

volumes:
  llm_apis_postgres:
