# CD Workflow
name: cd

# This workflow is expected to run whenever the commited code is pushed or PR is raised to the Master branch!
on:
  push:
    branches:
      - python

# This job is expected to run whenever the above condition is fulfilled!
jobs:
  dockerhub:
    name: Build, push to dockerhub

    # This job is required to run on ubuntu!
    runs-on: ubuntu-latest

    # Following are the steps which will be performed to complete this job!
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, Push
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/content_driven_llm_apis
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{env.DOCKERHUB_REPO}}:latest
